include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - sphexa_build
  - sphexa_unittests

# variables:
#   SPH_INSTALLDIR_DAINT: $SCRATCH
#   # CI_COMMIT_SHORT_SHA = /daint/ci/f148a2a4
